import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { NextAuthProvider } from "./lib/next-auth/provider";
import { getServerSession } from "next-auth/next";
import { authOptions } from "./lib/next-auth/options";

const notoSansJp = Noto_Sans_JP({ subsets: ["latin"], weight: ['400'] });

export const metadata: Metadata = {
  title: "Next E-book Store",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="ja">
      <body className={notoSansJp.className}>
        <NextAuthProvider>
          <Header user={session?.user} />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}